export const base = {
  '.prose': {
    '--base-size-4': '0.25rem',
    '--base-size-8': '0.5rem',
    '--base-size-16': '1rem',
    '--base-size-24': '1.5rem',
    '--base-size-40': '2.5rem',
    '--base-text-weight-normal': '400',
    '--base-text-weight-medium': '500',
    '--base-text-weight-semibold': '600',
    '--fontStack-monospace': 'ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace',
    '--fgColor-accent': 'Highlight',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
    margin: '0',
    color: 'var(--fgColor-default)',
    backgroundColor: 'var(--bgColor-default)',
    fontFamily:
      '-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"',
    fontSize: '16px',
    lineHeight: '1.5',
    wordWrap: 'break-word',
  },
}

export const light = {
  '.prose': {
    colorScheme: 'light',
    '--focus-outlineColor': '#0969da',
    '--fgColor-default': '#1f2328',
    '--fgColor-muted': '#59636e',
    '--fgColor-accent': '#0969da',
    '--fgColor-success': '#1a7f37',
    '--fgColor-attention': '#9a6700',
    '--fgColor-danger': '#d1242f',
    '--fgColor-done': '#8250df',
    '--bgColor-default': '#ffffff',
    '--bgColor-muted': '#f6f8fa',
    '--bgColor-neutral-muted': '#818b981f',
    '--bgColor-attention-muted': '#fff8c5',
    '--borderColor-default': '#d1d9e0',
    '--borderColor-muted': '#d1d9e0b3',
    '--borderColor-neutral-muted': '#d1d9e0b3',
    '--borderColor-accent-emphasis': '#0969da',
    '--borderColor-success-emphasis': '#1a7f37',
    '--borderColor-attention-emphasis': '#9a6700',
    '--borderColor-danger-emphasis': '#cf222e',
    '--borderColor-done-emphasis': '#8250df',
    '--color-prettylights-syntax-comment': '#59636e',
    '--color-prettylights-syntax-constant': '#0550ae',
    '--color-prettylights-syntax-constant-other-reference-link': '#0a3069',
    '--color-prettylights-syntax-entity': '#6639ba',
    '--color-prettylights-syntax-storage-modifier-import': '#1f2328',
    '--color-prettylights-syntax-entity-tag': '#0550ae',
    '--color-prettylights-syntax-keyword': '#cf222e',
    '--color-prettylights-syntax-string': '#0a3069',
    '--color-prettylights-syntax-variable': '#953800',
    '--color-prettylights-syntax-brackethighlighter-unmatched': '#82071e',
    '--color-prettylights-syntax-brackethighlighter-angle': '#59636e',
    '--color-prettylights-syntax-invalid-illegal-text': '#f6f8fa',
    '--color-prettylights-syntax-invalid-illegal-bg': '#82071e',
    '--color-prettylights-syntax-carriage-return-text': '#f6f8fa',
    '--color-prettylights-syntax-carriage-return-bg': '#cf222e',
    '--color-prettylights-syntax-string-regexp': '#116329',
    '--color-prettylights-syntax-markup-list': '#3b2300',
    '--color-prettylights-syntax-markup-heading': '#0550ae',
    '--color-prettylights-syntax-markup-italic': '#1f2328',
    '--color-prettylights-syntax-markup-bold': '#1f2328',
    '--color-prettylights-syntax-markup-deleted-text': '#82071e',
    '--color-prettylights-syntax-markup-deleted-bg': '#ffebe9',
    '--color-prettylights-syntax-markup-inserted-text': '#116329',
    '--color-prettylights-syntax-markup-inserted-bg': '#dafbe1',
    '--color-prettylights-syntax-markup-changed-text': '#953800',
    '--color-prettylights-syntax-markup-changed-bg': '#ffd8b5',
    '--color-prettylights-syntax-markup-ignored-text': '#d1d9e0',
    '--color-prettylights-syntax-markup-ignored-bg': '#0550ae',
    '--color-prettylights-syntax-meta-diff-range': '#8250df',
    '--color-prettylights-syntax-sublimelinter-gutter-mark': '#818b98',
  },
}

export const dark = {
  '.prose-invert': {
    colorScheme: 'dark',
    '--focus-outlineColor': '#1f6feb',
    '--fgColor-default': '#f0f6fc',
    '--fgColor-muted': '#9198a1',
    '--fgColor-accent': '#4493f8',
    '--fgColor-success': '#3fb950',
    '--fgColor-attention': '#d29922',
    '--fgColor-danger': '#f85149',
    '--fgColor-done': '#ab7df8',
    '--bgColor-default': '#0d1117',
    '--bgColor-muted': '#151b23',
    '--bgColor-neutral-muted': '#656c7633',
    '--bgColor-attention-muted': '#bb800926',
    '--borderColor-default': '#3d444d',
    '--borderColor-muted': '#3d444db3',
    '--borderColor-neutral-muted': '#3d444db3',
    '--borderColor-accent-emphasis': '#1f6feb',
    '--borderColor-success-emphasis': '#238636',
    '--borderColor-attention-emphasis': '#9e6a03',
    '--borderColor-danger-emphasis': '#da3633',
    '--borderColor-done-emphasis': '#8957e5',
    '--color-prettylights-syntax-comment': '#9198a1',
    '--color-prettylights-syntax-constant': '#79c0ff',
    '--color-prettylights-syntax-constant-other-reference-link': '#a5d6ff',
    '--color-prettylights-syntax-entity': '#d2a8ff',
    '--color-prettylights-syntax-storage-modifier-import': '#f0f6fc',
    '--color-prettylights-syntax-entity-tag': '#7ee787',
    '--color-prettylights-syntax-keyword': '#ff7b72',
    '--color-prettylights-syntax-string': '#a5d6ff',
    '--color-prettylights-syntax-variable': '#ffa657',
    '--color-prettylights-syntax-brackethighlighter-unmatched': '#f85149',
    '--color-prettylights-syntax-brackethighlighter-angle': '#9198a1',
    '--color-prettylights-syntax-invalid-illegal-text': '#f0f6fc',
    '--color-prettylights-syntax-invalid-illegal-bg': '#8e1519',
    '--color-prettylights-syntax-carriage-return-text': '#f0f6fc',
    '--color-prettylights-syntax-carriage-return-bg': '#b62324',
    '--color-prettylights-syntax-string-regexp': '#7ee787',
    '--color-prettylights-syntax-markup-list': '#f2cc60',
    '--color-prettylights-syntax-markup-heading': '#1f6feb',
    '--color-prettylights-syntax-markup-italic': '#f0f6fc',
    '--color-prettylights-syntax-markup-bold': '#f0f6fc',
    '--color-prettylights-syntax-markup-deleted-text': '#ffdcd7',
    '--color-prettylights-syntax-markup-deleted-bg': '#67060c',
    '--color-prettylights-syntax-markup-inserted-text': '#aff5b4',
    '--color-prettylights-syntax-markup-inserted-bg': '#033a16',
    '--color-prettylights-syntax-markup-changed-text': '#ffdfb6',
    '--color-prettylights-syntax-markup-changed-bg': '#5a1e02',
    '--color-prettylights-syntax-markup-ignored-text': '#f0f6fc',
    '--color-prettylights-syntax-markup-ignored-bg': '#1158c7',
    '--color-prettylights-syntax-meta-diff-range': '#d2a8ff',
    '--color-prettylights-syntax-sublimelinter-gutter-mark': '#3d444d',
  },
}

export const styles = {
  '.prose .octicon': {
    display: 'inline-block',
    fill: 'currentColor',
    verticalAlign: 'text-bottom',
    overflow: 'visible !important',
  },
  '.prose h1:hover .anchor .octicon-link:before,\n.prose h2:hover .anchor .octicon-link:before,\n.prose h3:hover .anchor .octicon-link:before,\n.prose h4:hover .anchor .octicon-link:before,\n.prose h5:hover .anchor .octicon-link:before,\n.prose h6:hover .anchor .octicon-link:before':
    {
      width: '16px',
      height: '16px',
      content: "' '",
      display: 'inline-block',
      backgroundColor: 'currentColor',
      WebkitMaskImage:
        "url(\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' version='1.1' aria-hidden='true'><path fill-rule='evenodd' d='M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z'></path></svg>\")",
      maskImage:
        "url(\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' version='1.1' aria-hidden='true'><path fill-rule='evenodd' d='M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z'></path></svg>\")",
    },
  '.prose details,\n.prose figcaption,\n.prose figure': {
    display: 'block',
  },
  '.prose summary': { display: 'list-item' },
  '.prose [hidden]': { display: 'none !important' },
  '.prose a': {
    backgroundColor: 'transparent',
    color: 'var(--fgColor-accent)',
    textDecoration: 'none',
  },
  '.prose abbr[title]': {
    borderBottom: 'none',
    WebkitTextDecoration: 'underline dotted',
    textDecoration: 'underline dotted',
  },
  '.prose b,\n.prose strong': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
  },
  '.prose dfn': { fontStyle: 'italic' },
  '.prose h1': {
    margin: '.67em 0',
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    paddingBottom: '.3em',
    fontSize: '2em',
    borderBottom: '1px solid var(--borderColor-muted)',
  },
  '.prose mark': {
    backgroundColor: 'var(--bgColor-attention-muted)',
    color: 'var(--fgColor-default)',
  },
  '.prose small': { fontSize: '90%' },
  '.prose sub,\n.prose sup': {
    fontSize: '75%',
    lineHeight: 0,
    position: 'relative',
    verticalAlign: 'baseline',
  },
  '.prose sub': { bottom: '-0.25em' },
  '.prose sup': { top: '-0.5em' },
  '.prose img': {
    borderStyle: 'none',
    maxWidth: '100%',
    boxSizing: 'content-box',
  },
  '.prose code,\n.prose kbd,\n.prose pre,\n.prose samp': {
    fontFamily: 'monospace',
    fontSize: '1em',
  },
  '.prose figure': { margin: '1em var(--base-size-40)' },
  '.prose hr': {
    boxSizing: 'content-box',
    overflow: 'hidden',
    background: 'transparent',
    borderBottom: '1px solid var(--borderColor-muted)',
    height: '.25em',
    padding: '0',
    margin: 'var(--base-size-24) 0',
    backgroundColor: 'var(--borderColor-default)',
    border: '0',
  },
  '.prose input': {
    font: 'inherit',
    margin: '0',
    overflow: 'visible',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 'inherit',
  },
  '.prose [type=button],\n.prose [type=reset],\n.prose [type=submit]': {
    WebkitAppearance: 'button',
    appearance: 'button',
  },
  '.prose [type=checkbox],\n.prose [type=radio]': {
    boxSizing: 'border-box',
    padding: '0',
  },
  '.prose [type=number]::-webkit-inner-spin-button,\n.prose [type=number]::-webkit-outer-spin-button': {
    height: 'auto',
  },
  '.prose [type=search]::-webkit-search-cancel-button,\n.prose [type=search]::-webkit-search-decoration': {
    WebkitAppearance: 'none',
    appearance: 'none',
  },
  '.prose ::-webkit-input-placeholder': {
    color: 'inherit',
    opacity: 0.54,
  },
  '.prose ::-webkit-file-upload-button': {
    WebkitAppearance: 'button',
    appearance: 'button',
    font: 'inherit',
  },
  '.prose a:hover': { textDecoration: 'underline' },
  '.prose ::placeholder': { color: 'var(--fgColor-muted)', opacity: 1 },
  '.prose hr::before': { display: 'table', content: '""' },
  '.prose hr::after': {
    display: 'table',
    clear: 'both',
    content: '""',
  },
  '.prose table': {
    borderSpacing: '0',
    borderCollapse: 'collapse',
    display: 'block',
    width: 'max-content',
    maxWidth: '100%',
    overflow: 'auto',
    fontVariant: 'tabular-nums',
  },
  '.prose td,\n.prose th': { padding: '0' },
  '.prose details summary': { cursor: 'pointer' },
  '.prose a:focus,\n.prose [role=button]:focus,\n.prose input[type=radio]:focus,\n.prose input[type=checkbox]:focus': {
    outline: '2px solid var(--focus-outlineColor)',
    outlineOffset: '-2px',
    boxShadow: 'none',
  },
  '.prose a:focus:not(:focus-visible),\n.prose [role=button]:focus:not(:focus-visible),\n.prose input[type=radio]:focus:not(:focus-visible),\n.prose input[type=checkbox]:focus:not(:focus-visible)':
    {
      outline: 'solid 1px transparent',
    },
  '.prose a:focus-visible,\n.prose [role=button]:focus-visible,\n.prose input[type=radio]:focus-visible,\n.prose input[type=checkbox]:focus-visible':
    {
      outline: '2px solid var(--focus-outlineColor)',
      outlineOffset: '-2px',
      boxShadow: 'none',
    },
  '.prose a:not([class]):focus,\n.prose a:not([class]):focus-visible,\n.prose input[type=radio]:focus,\n.prose input[type=radio]:focus-visible,\n.prose input[type=checkbox]:focus,\n.prose input[type=checkbox]:focus-visible':
    {
      outlineOffset: '0',
    },
  '.prose kbd': {
    display: 'inline-block',
    padding: 'var(--base-size-4)',
    font: '11px var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace)',
    lineHeight: '10px',
    color: 'var(--fgColor-default)',
    verticalAlign: 'middle',
    backgroundColor: 'var(--bgColor-muted)',
    border: 'solid 1px var(--borderColor-neutral-muted)',
    borderBottomColor: 'var(--borderColor-neutral-muted)',
    borderRadius: '6px',
    boxShadow: 'inset 0 -1px 0 var(--borderColor-neutral-muted)',
  },
  '.prose h1,\n.prose h2,\n.prose h3,\n.prose h4,\n.prose h5,\n.prose h6': {
    marginTop: 'var(--base-size-24)',
    marginBottom: 'var(--base-size-16)',
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    lineHeight: 1.25,
  },
  '.prose h2': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    paddingBottom: '.3em',
    fontSize: '1.5em',
    borderBottom: '1px solid var(--borderColor-muted)',
  },
  '.prose h3': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    fontSize: '1.25em',
  },
  '.prose h4': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    fontSize: '1em',
  },
  '.prose h5': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    fontSize: '.875em',
  },
  '.prose h6': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    fontSize: '.85em',
    color: 'var(--fgColor-muted)',
  },
  '.prose p': { marginTop: '0', marginBottom: '10px' },
  '.prose blockquote': {
    margin: '0',
    padding: '0 1em',
    color: 'var(--fgColor-muted)',
    borderLeft: '.25em solid var(--borderColor-default)',
  },
  '.prose ul,\n.prose ol': {
    marginTop: '0',
    marginBottom: '0',
    paddingLeft: '2em',
  },
  '.prose ol ol,\n.prose ul ol': {
    listStyleType: 'lower-roman',
  },
  '.prose ul ul ol,\n.prose ul ol ol,\n.prose ol ul ol,\n.prose ol ol ol': {
    listStyleType: 'lower-alpha',
  },
  '.prose dd': { marginLeft: '0' },
  '.prose tt,\n.prose code,\n.prose samp': {
    fontFamily:
      'var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace)',
    fontSize: '12px',
  },
  '.prose pre': {
    marginTop: '0',
    marginBottom: '0',
    fontFamily:
      'var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace)',
    fontSize: '12px',
    wordWrap: 'normal',
  },
  '.prose input::-webkit-outer-spin-button,\n.prose input::-webkit-inner-spin-button': {
    margin: '0',
    appearance: 'none',
  },
  '.prose .mr-2': { marginRight: 'var(--base-size-8, 8px) !important' },
  '.prose::before': { display: 'table', content: '""' },
  '.prose::after': { display: 'table', clear: 'both', content: '""' },
  '.prose>*:first-child': { marginTop: '0 !important' },
  '.prose>*:last-child': { marginBottom: '0 !important' },
  '.prose a:not([href])': { color: 'inherit', textDecoration: 'none' },
  '.prose .absent': { color: 'var(--fgColor-danger)' },
  '.prose .anchor': {
    cssFloat: 'left',
    paddingRight: 'var(--base-size-4)',
    marginLeft: '-20px',
    lineHeight: 1,
  },
  '.prose .anchor:focus': { outline: 'none' },
  '.prose p,\n.prose blockquote,\n.prose ul,\n.prose ol,\n.prose dl,\n.prose table,\n.prose pre,\n.prose details': {
    marginTop: '0',
    marginBottom: 'var(--base-size-16)',
  },
  '.prose blockquote>:first-child': { marginTop: '0' },
  '.prose blockquote>:last-child': { marginBottom: '0' },
  '.prose h1 .octicon-link,\n.prose h2 .octicon-link,\n.prose h3 .octicon-link,\n.prose h4 .octicon-link,\n.prose h5 .octicon-link,\n.prose h6 .octicon-link':
    {
      color: 'var(--fgColor-default)',
      verticalAlign: 'middle',
      visibility: 'hidden',
    },
  '.prose h1:hover .anchor,\n.prose h2:hover .anchor,\n.prose h3:hover .anchor,\n.prose h4:hover .anchor,\n.prose h5:hover .anchor,\n.prose h6:hover .anchor':
    {
      textDecoration: 'none',
    },
  '.prose h1:hover .anchor .octicon-link,\n.prose h2:hover .anchor .octicon-link,\n.prose h3:hover .anchor .octicon-link,\n.prose h4:hover .anchor .octicon-link,\n.prose h5:hover .anchor .octicon-link,\n.prose h6:hover .anchor .octicon-link':
    {
      visibility: 'visible',
    },
  '.prose h1 tt,\n.prose h1 code,\n.prose h2 tt,\n.prose h2 code,\n.prose h3 tt,\n.prose h3 code,\n.prose h4 tt,\n.prose h4 code,\n.prose h5 tt,\n.prose h5 code,\n.prose h6 tt,\n.prose h6 code':
    {
      padding: '0 .2em',
      fontSize: 'inherit',
    },
  '.prose summary h1,\n.prose summary h2,\n.prose summary h3,\n.prose summary h4,\n.prose summary h5,\n.prose summary h6':
    {
      display: 'inline-block',
    },
  '.prose summary h1 .anchor,\n.prose summary h2 .anchor,\n.prose summary h3 .anchor,\n.prose summary h4 .anchor,\n.prose summary h5 .anchor,\n.prose summary h6 .anchor':
    {
      marginLeft: '-40px',
    },
  '.prose summary h1,\n.prose summary h2': {
    paddingBottom: '0',
    borderBottom: '0',
  },
  '.prose ul.no-list,\n.prose ol.no-list': {
    padding: '0',
    listStyleType: 'none',
  },
  '.prose ol[type="a s"]': { listStyleType: 'lower-alpha' },
  '.prose ol[type="A s"]': { listStyleType: 'upper-alpha' },
  '.prose ol[type="i s"]': { listStyleType: 'lower-roman' },
  '.prose ol[type="I s"]': { listStyleType: 'upper-roman' },
  '.prose ol[type="1"]': { listStyleType: 'decimal' },
  '.prose div>ol:not([type])': { listStyleType: 'decimal' },
  '.prose ul ul,\n.prose ul ol,\n.prose ol ol,\n.prose ol ul': {
    marginTop: '0',
    marginBottom: '0',
  },
  '.prose li>p': { marginTop: 'var(--base-size-16)' },
  '.prose li+li': { marginTop: '.25em' },
  '.prose dl': { padding: '0' },
  '.prose dl dt': {
    padding: '0',
    marginTop: 'var(--base-size-16)',
    fontSize: '1em',
    fontStyle: 'italic',
    fontWeight: 'var(--base-text-weight-semibold, 600)',
  },
  '.prose dl dd': {
    padding: '0 var(--base-size-16)',
    marginBottom: 'var(--base-size-16)',
  },
  '.prose table th': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
  },
  '.prose table th,\n.prose table td': {
    padding: '6px 13px',
    border: '1px solid var(--borderColor-default)',
  },
  '.prose table td>:last-child': { marginBottom: '0' },
  '.prose table tr': {
    backgroundColor: 'var(--bgColor-default)',
    borderTop: '1px solid var(--borderColor-muted)',
  },
  '.prose table tr:nth-child(2n)': {
    backgroundColor: 'var(--bgColor-muted)',
  },
  '.prose table img': { backgroundColor: 'transparent' },
  '.prose img[align=right]': { paddingLeft: '20px' },
  '.prose img[align=left]': { paddingRight: '20px' },
  '.prose .emoji': {
    maxWidth: 'none',
    verticalAlign: 'text-top',
    backgroundColor: 'transparent',
  },
  '.prose span.frame': { display: 'block', overflow: 'hidden' },
  '.prose span.frame>span': {
    display: 'block',
    cssFloat: 'left',
    width: 'auto',
    padding: '7px',
    margin: '13px 0 0',
    overflow: 'hidden',
    border: '1px solid var(--borderColor-default)',
  },
  '.prose span.frame span img': { display: 'block', cssFloat: 'left' },
  '.prose span.frame span span': {
    display: 'block',
    padding: '5px 0 0',
    clear: 'both',
    color: 'var(--fgColor-default)',
  },
  '.prose span.align-center': {
    display: 'block',
    overflow: 'hidden',
    clear: 'both',
  },
  '.prose span.align-center>span': {
    display: 'block',
    margin: '13px auto 0',
    overflow: 'hidden',
    textAlign: 'center',
  },
  '.prose span.align-center span img': {
    margin: '0 auto',
    textAlign: 'center',
  },
  '.prose span.align-right': {
    display: 'block',
    overflow: 'hidden',
    clear: 'both',
  },
  '.prose span.align-right>span': {
    display: 'block',
    margin: '13px 0 0',
    overflow: 'hidden',
    textAlign: 'right',
  },
  '.prose span.align-right span img': {
    margin: '0',
    textAlign: 'right',
  },
  '.prose span.float-left': {
    display: 'block',
    cssFloat: 'left',
    marginRight: '13px',
    overflow: 'hidden',
  },
  '.prose span.float-left span': { margin: '13px 0 0' },
  '.prose span.float-right': {
    display: 'block',
    cssFloat: 'right',
    marginLeft: '13px',
    overflow: 'hidden',
  },
  '.prose span.float-right>span': {
    display: 'block',
    margin: '13px auto 0',
    overflow: 'hidden',
    textAlign: 'right',
  },
  '.prose code,\n.prose tt': {
    padding: '.2em .4em',
    margin: '0',
    fontSize: '85%',
    whiteSpace: 'break-spaces',
    backgroundColor: 'var(--bgColor-neutral-muted)',
    borderRadius: '6px',
  },
  '.prose code br,\n.prose tt br': { display: 'none' },
  '.prose del code': { textDecoration: 'inherit' },
  '.prose samp': { fontSize: '85%' },
  '.prose pre code': { fontSize: '100%' },
  '.prose pre>code': {
    padding: '0',
    margin: '0',
    wordBreak: 'normal',
    whiteSpace: 'pre',
    background: 'transparent',
    border: '0',
  },
  '.prose .highlight': { marginBottom: 'var(--base-size-16)' },
  '.prose .highlight pre': { marginBottom: '0', wordBreak: 'normal' },
  '.prose .highlight pre,\n.prose pre': {
    padding: 'var(--base-size-16)',
    overflow: 'auto',
    fontSize: '85%',
    lineHeight: 1.45,
    color: 'var(--fgColor-default)',
    backgroundColor: 'var(--bgColor-muted)',
    borderRadius: '6px',
  },
  '.prose pre code,\n.prose pre tt': {
    display: 'inline',
    maxWidth: 'auto',
    padding: '0',
    margin: '0',
    overflow: 'visible',
    lineHeight: 'inherit',
    wordWrap: 'normal',
    backgroundColor: 'transparent',
    border: '0',
  },
  '.prose .csv-data td,\n.prose .csv-data th': {
    padding: '5px',
    overflow: 'hidden',
    fontSize: '12px',
    lineHeight: 1,
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  '.prose .csv-data .blob-num': {
    padding: '10px var(--base-size-8) 9px',
    textAlign: 'right',
    background: 'var(--bgColor-default)',
    border: '0',
  },
  '.prose .csv-data tr': { borderTop: '0' },
  '.prose .csv-data th': {
    fontWeight: 'var(--base-text-weight-semibold, 600)',
    background: 'var(--bgColor-muted)',
    borderTop: '0',
  },
  '.prose [data-footnote-ref]::before': { content: '"["' },
  '.prose [data-footnote-ref]::after': { content: '"]"' },
  '.prose .footnotes': {
    fontSize: '12px',
    color: 'var(--fgColor-muted)',
    borderTop: '1px solid var(--borderColor-default)',
  },
  '.prose .footnotes ol': { paddingLeft: 'var(--base-size-16)' },
  '.prose .footnotes ol ul': {
    display: 'inline-block',
    paddingLeft: 'var(--base-size-16)',
    marginTop: 'var(--base-size-16)',
  },
  '.prose .footnotes li': { position: 'relative' },
  '.prose .footnotes li:target::before': {
    position: 'absolute',
    top: 'calc(var(--base-size-8)*-1)',
    right: 'calc(var(--base-size-8)*-1)',
    bottom: 'calc(var(--base-size-8)*-1)',
    left: 'calc(var(--base-size-24)*-1)',
    pointerEvents: 'none',
    content: '""',
    border: '2px solid var(--borderColor-accent-emphasis)',
    borderRadius: '6px',
  },
  '.prose .footnotes li:target': { color: 'var(--fgColor-default)' },
  '.prose .footnotes .data-footnote-backref g-emoji': {
    fontFamily: 'monospace',
  },
  '.prose body:has(:modal)': {
    paddingRight: 'var(--dialog-scrollgutter) !important',
  },
  '.prose .pl-c': { color: 'var(--color-prettylights-syntax-comment)' },
  '.prose .pl-c1,\n.prose .pl-s .pl-v': {
    color: 'var(--color-prettylights-syntax-constant)',
  },
  '.prose .pl-e,\n.prose .pl-en': {
    color: 'var(--color-prettylights-syntax-entity)',
  },
  '.prose .pl-smi,\n.prose .pl-s .pl-s1': {
    color: 'var(--color-prettylights-syntax-storage-modifier-import)',
  },
  '.prose .pl-ent': {
    color: 'var(--color-prettylights-syntax-entity-tag)',
  },
  '.prose .pl-k': { color: 'var(--color-prettylights-syntax-keyword)' },
  '.prose .pl-s,\n.prose .pl-pds,\n.prose .pl-s .pl-pse .pl-s1,\n.prose .pl-sr,\n.prose .pl-sr .pl-cce,\n.prose .pl-sr .pl-sre,\n.prose .pl-sr .pl-sra':
    {
      color: 'var(--color-prettylights-syntax-string)',
    },
  '.prose .pl-v,\n.prose .pl-smw': {
    color: 'var(--color-prettylights-syntax-variable)',
  },
  '.prose .pl-bu': {
    color: 'var(--color-prettylights-syntax-brackethighlighter-unmatched)',
  },
  '.prose .pl-ii': {
    color: 'var(--color-prettylights-syntax-invalid-illegal-text)',
    backgroundColor: 'var(--color-prettylights-syntax-invalid-illegal-bg)',
  },
  '.prose .pl-c2': {
    color: 'var(--color-prettylights-syntax-carriage-return-text)',
    backgroundColor: 'var(--color-prettylights-syntax-carriage-return-bg)',
  },
  '.prose .pl-sr .pl-cce': {
    fontWeight: 'bold',
    color: 'var(--color-prettylights-syntax-string-regexp)',
  },
  '.prose .pl-ml': {
    color: 'var(--color-prettylights-syntax-markup-list)',
  },
  '.prose .pl-mh,\n.prose .pl-mh .pl-en,\n.prose .pl-ms': {
    fontWeight: 'bold',
    color: 'var(--color-prettylights-syntax-markup-heading)',
  },
  '.prose .pl-mi': {
    fontStyle: 'italic',
    color: 'var(--color-prettylights-syntax-markup-italic)',
  },
  '.prose .pl-mb': {
    fontWeight: 'bold',
    color: 'var(--color-prettylights-syntax-markup-bold)',
  },
  '.prose .pl-md': {
    color: 'var(--color-prettylights-syntax-markup-deleted-text)',
    backgroundColor: 'var(--color-prettylights-syntax-markup-deleted-bg)',
  },
  '.prose .pl-mi1': {
    color: 'var(--color-prettylights-syntax-markup-inserted-text)',
    backgroundColor: 'var(--color-prettylights-syntax-markup-inserted-bg)',
  },
  '.prose .pl-mc': {
    color: 'var(--color-prettylights-syntax-markup-changed-text)',
    backgroundColor: 'var(--color-prettylights-syntax-markup-changed-bg)',
  },
  '.prose .pl-mi2': {
    color: 'var(--color-prettylights-syntax-markup-ignored-text)',
    backgroundColor: 'var(--color-prettylights-syntax-markup-ignored-bg)',
  },
  '.prose .pl-mdr': {
    fontWeight: 'bold',
    color: 'var(--color-prettylights-syntax-meta-diff-range)',
  },
  '.prose .pl-ba': {
    color: 'var(--color-prettylights-syntax-brackethighlighter-angle)',
  },
  '.prose .pl-sg': {
    color: 'var(--color-prettylights-syntax-sublimelinter-gutter-mark)',
  },
  '.prose .pl-corl': {
    textDecoration: 'underline',
    color: 'var(--color-prettylights-syntax-constant-other-reference-link)',
  },
  '.prose [role=button]:focus:not(:focus-visible),\n.prose [role=tabpanel][tabindex="0"]:focus:not(:focus-visible),\n.prose button:focus:not(:focus-visible),\n.prose summary:focus:not(:focus-visible),\n.prose a:focus:not(:focus-visible)':
    {
      outline: 'none',
      boxShadow: 'none',
    },
  '.prose [tabindex="0"]:focus:not(:focus-visible),\n.prose details-dialog:focus:not(:focus-visible)': {
    outline: 'none',
  },
  '.prose g-emoji': {
    display: 'inline-block',
    minWidth: '1ch',
    fontFamily: '"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"',
    fontSize: '1em',
    fontStyle: 'normal !important',
    fontWeight: 'var(--base-text-weight-normal, 400)',
    lineHeight: 1,
    verticalAlign: '-0.075em',
  },
  '.prose g-emoji img': { width: '1em', height: '1em' },
  '.prose .task-list-item': { listStyleType: 'none' },
  '.prose .task-list-item label': {
    fontWeight: 'var(--base-text-weight-normal, 400)',
  },
  '.prose .task-list-item.enabled label': { cursor: 'pointer' },
  '.prose .task-list-item+.task-list-item': {
    marginTop: 'var(--base-size-4)',
  },
  '.prose .task-list-item .handle': { display: 'none' },
  '.prose .task-list-item-checkbox': {
    margin: '0 .2em .25em -1.4em',
    verticalAlign: 'middle',
  },
  '.prose ul:dir(rtl) .task-list-item-checkbox': {
    margin: '0 -1.6em .25em .2em',
  },
  '.prose ol:dir(rtl) .task-list-item-checkbox': {
    margin: '0 -1.6em .25em .2em',
  },
  '.prose .contains-task-list:hover .task-list-item-convert-container,\n.prose .contains-task-list:focus-within .task-list-item-convert-container':
    {
      display: 'block',
      width: 'auto',
      height: '24px',
      overflow: 'visible',
      clip: 'auto',
    },
  '.prose ::-webkit-calendar-picker-indicator': {
    filter: 'invert(50%)',
  },
  '.prose .markdown-alert': {
    padding: 'var(--base-size-8) var(--base-size-16)',
    marginBottom: 'var(--base-size-16)',
    color: 'inherit',
    borderLeft: '.25em solid var(--borderColor-default)',
  },
  '.prose .markdown-alert>:first-child': { marginTop: '0' },
  '.prose .markdown-alert>:last-child': { marginBottom: '0' },
  '.prose .markdown-alert .markdown-alert-title': {
    display: 'flex',
    fontWeight: 'var(--base-text-weight-medium, 500)',
    alignItems: 'center',
    lineHeight: 1,
  },
  '.prose .markdown-alert.markdown-alert-note': {
    borderLeftColor: 'var(--borderColor-accent-emphasis)',
  },
  '.prose .markdown-alert.markdown-alert-note .markdown-alert-title': {
    color: 'var(--fgColor-accent)',
  },
  '.prose .markdown-alert.markdown-alert-important': {
    borderLeftColor: 'var(--borderColor-done-emphasis)',
  },
  '.prose .markdown-alert.markdown-alert-important .markdown-alert-title': {
    color: 'var(--fgColor-done)',
  },
  '.prose .markdown-alert.markdown-alert-warning': {
    borderLeftColor: 'var(--borderColor-attention-emphasis)',
  },
  '.prose .markdown-alert.markdown-alert-warning .markdown-alert-title': {
    color: 'var(--fgColor-attention)',
  },
  '.prose .markdown-alert.markdown-alert-tip': {
    borderLeftColor: 'var(--borderColor-success-emphasis)',
  },
  '.prose .markdown-alert.markdown-alert-tip .markdown-alert-title': {
    color: 'var(--fgColor-success)',
  },
  '.prose .markdown-alert.markdown-alert-caution': {
    borderLeftColor: 'var(--borderColor-danger-emphasis)',
  },
  '.prose .markdown-alert.markdown-alert-caution .markdown-alert-title': {
    color: 'var(--fgColor-danger)',
  },
  '.prose>*:first-child>.heading-element:first-child': {
    marginTop: '0 !important',
  },
  '.prose .highlight pre:has(+.zeroclipboard-container)': {
    minHeight: '52px',
  },
}
